Repository AY2223S2-CS2103T-T15-1/tp, pull requests merged in 2023-03, with the labels that each got.

#29 Add Entity
  src/main/java/seedu/address/model/entity/Entity.java
Labels: type.Task, priority.High

#28 Add ViewMode and ListMode
  docs/images/roultitude.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UiSwitchMode.java
  src/main/java/seedu/address/ui/EntityListPanel.java
  src/main/java/seedu/address/ui/ListModePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewModePanel.java
  src/main/resources/view/EntityListPanel.fxml
  src/main/resources/view/ListModePanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewModePanel.fxml
Labels: type.Task, priority.High

#56 Migrated to Entities and integrated view UI
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/experimental/model/Model.java
  src/main/java/seedu/address/experimental/model/ModelManager.java
  src/main/java/seedu/address/experimental/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/experimental/storage/Storage.java
  src/main/java/seedu/address/experimental/storage/StorageManager.java
  src/main/java/seedu/address/experimental/storage/UserPrefsStorage.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditValueCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddEntityCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModeParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/entity/Character.java
  src/main/java/seedu/address/model/entity/Mob.java
  src/main/java/seedu/address/model/entity/Stats.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/ui/EntityCard.java
  src/main/java/seedu/address/ui/EntityDetailsPanel.java
  src/main/java/seedu/address/ui/EntityListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ViewModePanel.java
  src/main/resources/view/EntityDetailsPanel.fxml
  src/main/resources/view/EntityListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#65 Add filter command
  src/main/java/seedu/address/experimental/model/Model.java
  src/main/java/seedu/address/experimental/model/ModelManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/util/ComposedPredicate.java
Labels: priority.High, type.Story

#63 Adjust styling and formatting of Entity Details Panel in Edit Mode
  src/main/java/seedu/address/experimental/storage/JsonAdaptedMob.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditValueCommand.java
  src/main/java/seedu/address/logic/parser/EditModeParser.java
  src/main/java/seedu/address/model/entity/Item.java
  src/main/java/seedu/address/model/entity/Mob.java
  src/main/java/seedu/address/ui/EntityDetailsPanel.java
  src/main/java/seedu/address/ui/EntityListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DnD.css
  src/main/resources/view/EntityDetailsPanel.fxml
  src/main/resources/view/EntityListPanel.fxml
  src/main/resources/view/ViewModePanel.fxml
Labels: priority.Medium

#70 Remove unused AB3 storage and model classes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
Labels: type.Task, priority.High

#86 Update AB3 Documentation
  docs/DeveloperGuide.md
  docs/diagrams/.idea/misc.xml
  docs/diagrams/.idea/workspace.xml
  docs/diagrams/reroll/RerollArchitectureSequenceDiagram.puml
  docs/diagrams/reroll/RerollStorageSequenceDiagram.puml
  docs/diagrams/reroll/style.puml
  docs/images/RerollArchitectureSequenceDiagram.png
  docs/images/RerollStorageSequenceDiagram.png
  docs/images/Reroll_Banner.png
Labels: priority.Medium

#92 Update DG for Ui and Edit mode Logic
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/reroll/RerollEditModeSequenceDiagram.puml
  docs/diagrams/reroll/RerollLogicActivityDiagram.puml
  docs/diagrams/reroll/RerollUiClassDiagram.puml
  docs/images/RerollEditModeSequenceDiagram.png
  docs/images/RerollEntityClassDiagram.png
  docs/images/RerollLogicActivityDiagram.png
  docs/images/RerollModelClassDiagram.png
  docs/images/RerollStorageClassDiagram.png
  docs/images/RerollUiClassDiagram.png
Labels: type.Task, priority.Medium

#95 Refactor delete command (closes #94)
  src/main/java/seedu/address/experimental/model/Model.java
  src/main/java/seedu/address/experimental/model/ModelManager.java
  src/main/java/seedu/address/experimental/model/Reroll.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MakeCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MakeCommandParser.java
  src/main/java/seedu/address/logic/parser/RerollParser.java
Labels: priority.High, type.Story

#93 Add Header to DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#110 Update initial draft for v1.3 release
  docs/UserGuide.md
Labels: type.Task, priority.High

#107 Add template features
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/experimental/model/Model.java
  src/main/java/seedu/address/experimental/model/ModelManager.java
  src/main/java/seedu/address/experimental/model/ReadOnlyReroll.java
  src/main/java/seedu/address/experimental/model/Reroll.java
  src/main/java/seedu/address/experimental/model/RerollItems.java
  src/main/java/seedu/address/experimental/model/RerollTemplates.java
  src/main/java/seedu/address/experimental/model/UniqueTemplateList.java
  src/main/java/seedu/address/experimental/model/util/BasicTemplates.java
  src/main/java/seedu/address/experimental/model/util/SampleDataUtil.java
  src/main/java/seedu/address/experimental/storage/JsonAdaptedCharacter.java
  src/main/java/seedu/address/experimental/storage/JsonAdaptedTemplate.java
  src/main/java/seedu/address/experimental/storage/JsonSerializableReroll.java
  src/main/java/seedu/address/logic/commands/EditValueCommand.java
  src/main/java/seedu/address/logic/commands/ShowTemplatesCommand.java
  src/main/java/seedu/address/logic/commands/TemplateCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/MakeCommandParser.java
  src/main/java/seedu/address/logic/parser/RerollParser.java
  src/main/java/seedu/address/logic/parser/TemplateCommandParser.java
  src/main/java/seedu/address/model/entity/Character.java
  src/main/java/seedu/address/model/entity/Classification.java
  src/main/java/seedu/address/model/entity/Entity.java
  src/main/java/seedu/address/model/entity/Mob.java
  src/main/java/seedu/address/model/entity/Template.java
  src/main/java/seedu/address/model/entity/exceptions/DuplicateTemplateException.java
  src/test/java/seedu/address/logic/commands/MakeCommandTest.java
  src/test/java/seedu/address/testutil/EntityBuilder.java
Labels: type.Story, priority.Medium

#116 Add more short-form commands (closes #115)
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MakeCommand.java
  src/main/java/seedu/address/logic/commands/ShowTemplatesCommand.java
  src/main/java/seedu/address/logic/commands/TemplateCommand.java
  src/main/java/seedu/address/logic/parser/EditModeParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/MakeCommandParser.java
  src/main/java/seedu/address/logic/parser/RerollParser.java
  src/main/java/seedu/address/model/entity/Classification.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/MakeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RerollParserTest.java
  src/test/java/seedu/address/testutil/EntityUtil.java
Labels: type.Story, priority.Medium

#120 Add detailed toString
  src/main/java/seedu/address/logic/parser/EditModeParser.java
  src/main/java/seedu/address/model/entity/Entity.java
Labels: type.Enhancement, priority.Medium

#122 Fix classification icons not appearing when built to jar
  src/main/java/seedu/address/ui/EntityCard.java
Labels: type.Bug, severity.Low
